services:
  - postgres:14-alpine

variables:
  POSTGRES_USER: article-saver
  POSTGRES_DB: article-saver
  POSTGRES_PASSWORD: article-saver
  POSTGRES_HOST_AUTH_METHOD: trust
  TEST_DB: postgresql://article-saver:article-saver@postgres:5432

stages:
  - test
  - cargo:test:nightly
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

.install_openssl: &install_openssl |
  apt-get update
  apt-get install -y pkg-config libssl-dev

test:cargo:
  image: rust:1.61-slim-bullseye
  stage: test
  script:
    - *install_openssl
    - cd backend
    - cargo test

cargo:test:nightly:
  image: rustlang/rust:nightly
  stage: cargo:test:nightly
  script:
    - *install_openssl
    - cd backend
    - cargo test
  allow_failure: true
