[package]
name = "article-server-rs"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
html5ever = "0.25"
kuchiki = "0.8"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
sqlx = {version = "0.5", features = ["runtime-tokio-rustls", "sqlite", "migrate"]}
tokio = { version = "1", features = ["full"] }
warp = "0.3"
