FROM rust:1.57-slim-bullseye

RUN dpkg --add-architecture arm64 && \
	apt-get update && \
	apt-get install -y gcc-aarch64-linux-gnu pkg-config libssl-dev:arm64 && \
	rustup target add aarch64-unknown-linux-gnu

RUN useradd -m crosscompiler
USER crosscompiler
WORKDIR /home/crosscompiler

ENV RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc"
ENV PKG_CONFIG_SYSROOT_DIR=/usr/lib/aarch64-linux-gnu/
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig/:$PKG_CONFIG_PATH

COPY --chown=crosscompiler crosscompile.sh crosscompile.sh

VOLUME /src rust source file directory

# Usage: podman run -it --rm -v $PWD/:/src:Z --userns=keep-id crosscompile ./crosscompile.sh
